from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"
OUTPUT_DIR = PROJECT_ROOT / "outputs"
MODEL_DIR = PROJECT_ROOT / "models"

DATASET_CONFIG = DATA_DIR / "dataset.yaml"
DEFAULT_MODEL = "yolov8n.pt"
DEFAULT_IMAGE_SIZE = 640
DEFAULT_EPOCHS = 50
DEFAULT_CONFIDENCE = 0.25
DEFAULT_IOU = 0.45

CLASS_PERSON = "person"
CLASS_HELMET = "helmet"
CLASS_VEST = "vest"
SUPPORTED_CLASSES = {CLASS_PERSON, CLASS_HELMET, CLASS_VEST}

HEAD_REGION_RATIO = 0.30
TORSO_REGION_START_RATIO = 0.30
TORSO_REGION_END_RATIO = 0.75
